version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
      image: 'mysql:latest'
      environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: main
      ports:     
        - 6033:3306
      volumes:
      - ./school_db:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - database
    environment:
      PMA_HOST: database
      PMA_USER: root
      PMA_PASSWORD: password
      # PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80